

//GET  https://jsonplaceholder.typicode.com/posts 


Post http://localhost:5500/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation{
  deletePost(id:5){
    title
  }
}

# query{
#   findOnePost(id:1){
#     title
#   }
# }


# query{
#   findAllPosts{
#     title
#     body
#     id
#   }
# }

